comment on column public.inbound_compliance_rules.has_teeth is
  'True only when non-compliance carries monetary penalties or compels capital work. '
  'False = filing/disclosure obligation only. NULL = unknown; outreach must treat as false. '
  'A false value forbids fine/penalty language in any email citing this rule.';

update public.inbound_compliance_rules set must_do = v.must_do, has_teeth = v.has_teeth
from (values
  ('nyc_ll97',
   'meet a carbon emissions cap for each large building, with penalties per ton over the cap',
   true),
  ('nyc_ll11',
   'have building facades inspected by a qualified professional every five years, and repair anything filed as unsafe',
   true),
  ('nyc_ll88',
   'upgrade lighting to code and install tenant sub-meters in large buildings',
   true),
  ('nyc_ll84',
   'report whole-building energy and water use each year; the results are published',
   false),
  ('nyc_ll87',
   'complete an energy audit and retro-commissioning once every ten years and file the report',
   false),
  ('nyc_ll33_ll95',
   'post an energy efficiency letter grade at building entrances each year',
   false),
  ('boston_berdo',
   'report energy and water use each year and meet a declining emissions standard, or make an alternative compliance payment',
   true),
  ('dc_beps',
   'benchmark each year and either meet the performance standard or complete an approved compliance pathway',
   true),
  ('denver_energize',
   'benchmark each year and reach the building energy performance targets by 2030',
   true),
  ('la_ebewe',
   'benchmark each year and complete an energy and water audit or retro-commissioning every five years',
   true),
  ('philadelphia_bepp',
   'complete a building tune-up on schedule and file the results',
   true),
  ('seattle_beps',
   'meet the building emissions performance standard on the compliance schedule for the building size tier',
   true),
  ('wa_cbps',
   'meet the state energy use intensity target for the building tier and file a compliance report',
   true),
  ('md_beps',
   'report building energy use and emissions to MDE each year by June 1',
   true),
  ('chicago_beps',
   'report energy use each year; the results are published in the city benchmarking dataset',
   false),
  ('ma_lber',
   'report annual energy use for buildings over roughly 20,000 sq ft',
   false),
  ('philadelphia_benchmarking',
   'report annual energy and water use for large commercial buildings',
   false),
  ('seattle_energy_benchmarking',
   'report annual energy use to the city',
   false),
  ('arlington_va_benchmarking',
   'report annual energy use for covered commercial buildings',
   false),
  ('va_note',
   'nothing — Virginia has no statewide building performance mandate. Never cite a deadline or penalty here',
   false)
) as v(id, must_do, has_teeth)
where public.inbound_compliance_rules.id = v.id;
